from pptx import Presentation
import os

def create_basics_ppt(topic, content_points):
    prs = Presentation()
    
    # Title Slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = f"Basics of {topic}"
    slide.placeholders[1].text = "Generated by LearnMate AI"

    # Content Slides
    for point in content_points:
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = topic
        slide.placeholders[1].text = point

    filename = f"ppts/{topic.replace(' ', '_')}_basics.pptx"
    if not os.path.exists('ppts'): os.makedirs('ppts')
    prs.save(filename)
    return filename